### ISSUE TITLE
Unable to open preview in browser normally in WSL

### ISSUE THREAD

**Issue by Parsifa1** [chomosuke/typst-preview.nvim#5] opened 2023-12-06 11:56 UTC
![image](https://github.com/chomosuke/typst-preview.nvim/assets/31800073/a9cf7c10-b60a-4f70-97ae-ba6346df2828)
all the required are download

When using the ":TypstPreview" command,  nothing happened

**Comment by Parsifa1** [comment] 2023-12-06 12:07
It seems that my current working folder is not the folder where the typst file is located. Thank you for your plug-in. The problem is solved.

**Comment by Parsifa1** [comment] 2023-12-06 12:39
每当我在typst源文件中打出一个回车的时候，会出现这个错误：
![image](https://github.com/chomosuke/typst-preview.nvim/assets/31800073/7ed9f69b-dde8-4a9f-af14-41de01d32ce7)

**Comment by chomosuke** [comment] 2023-12-11 13:53
Hi, sorry I don't have time to attempt to reproduce your issue until this weekend. But this could be a fixed by #6

**Comment by chomosuke** [comment] 2023-12-16 10:17
Hello there, I've so far be unable to reproduce the issue, however it is possible that the recent release 0.1.2 fixed it. Feel free to reopen this issue if the new release did not fix the issue for you but do please provide more detail to help me reproduce your issue :).

**Closed by chomosuke** 2023-12-16 10:17 UTC

**Comment by Parsifa1** [comment] 2023-12-16 11:33
thanks a lot !
